services:
  knowme-ai:
    container_name: knowme-ai
    image: ghcr.io/lockhart07/knowme-ai:latest
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; r=requests.get('http://localhost:7000/ping'); r.raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_API_KEYS=${GOOGLE_API_KEYS}
      - DATOCMS_API_TOKEN=${DATOCMS_API_TOKEN}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash-lite}
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: knowme-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  redis_data: